### ISSUE TITLE
[Anon] Post-Human Republic: Says you can only have 3 Odysseus (PHR) but they're group 1-2, and you can have 2 groups of them at 1500 points

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dropfleet-commander-2024#3]
**Problem:**
Says you can only have 3 Odysseus (PHR) but they're group 1-2, and you can have 2 groups of them at 1500 points

**Expected:**
expected: 4 total (2 groups of 2)

**List:** https://www.newrecruit.eu/app/list/98e73

**Comment by Kemp-J** [comment]
The Rare special rule gives limits on the number of groups not the number of ships. In this case the Battle option has been selected for Game Size, which is limiting Rare ships to 3 groups each. This should also be raising a validation error due to the fleet being undersized. Set Game Size to Clash instead.
